on:
  push:
    branches-ignore:
      - main
      - master
      - ghpages

name: "check package"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      GITHUB_TOKEN: ${{ github.token }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: inbo/actions/check_pkg@token
